spring:
  mustache:
    suffix: .mustache
    prefix: classpath:/templates/
    servlet:
      cache: false
    charset: UTF-8


server:
  port: 8080

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}

logging:
  level:
    org.springframework.web: DEBUG